traffic_sign_node:
  ros__parameters:

    model_path: ''
    detection_topic:  /traffic_sign/detection
    image_topic:      /traffic_sign/image

    conf_threshold:   0.30
    iou_threshold:    0.40
    imgsz:            640

    depth_min_mm:     100
    depth_max_mm:     2000

    # Simulator mode: subscribe to ROS2 image topic instead of OAK or webcam
    use_mock_camera:  false
    use_sim:          true
    sim_image_topic:  /oak/rgb/image_raw

    trigger_dist_stop:             0.60
    trigger_dist_parking:          0.80
    trigger_dist_priority:         0.60
    trigger_dist_roundabout:       0.70
    trigger_dist_one_way:          0.70
    trigger_dist_no_entry:         0.80
    trigger_dist_exit_highway:     0.60
    trigger_dist_entrance_highway: 0.80
    trigger_dist_crosswalk:        0.50

    cooldown_stop:             5.0
    cooldown_parking:          8.0
    cooldown_priority:         4.0
    cooldown_roundabout:       5.0
    cooldown_one_way:          5.0
    cooldown_no_entry:         5.0
    cooldown_exit_highway:     8.0
    cooldown_entrance_highway: 8.0
    cooldown_crosswalk:        3.0

    debug_view: true
